# Generated by Django 4.2.3 on 2023-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=1
            ),
        ),
    ]
