# Generated by Django 4.2.3 on 2023-07-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_product_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="PModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("url", models.URLField(default="http://i.imgur.com/Ous4iGB.png")),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.maker"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="超值二手機", max_length=15)),
                ("description", models.TextField(default="暫無說明")),
                ("year", models.PositiveIntegerField(default=2016)),
                ("price", models.PositiveBigIntegerField(default=0)),
                (
                    "pmodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.pmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="產品照片", max_length=20)),
                ("url", models.CharField(default="", max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.product2",
                    ),
                ),
            ],
        ),
    ]
