# Generated by Django 4.2.3 on 2023-07-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_alter_product2_nickname_alter_product2_pmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Post2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="不願意透漏身份的人", max_length=10)),
                ("message", models.TextField()),
                ("del_pass", models.CharField(max_length=10)),
                ("pub_time", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "mood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.mood"
                    ),
                ),
            ],
        ),
    ]
