# Generated by Django 4.2.3 on 2023-07-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_mood_post2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post2",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
