# Generated by Django 4.2.3 on 2023-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0015_diary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("no", models.IntegerField()),
                ("sex", models.BooleanField(default=False)),
                ("byear", models.IntegerField()),
                ("party", models.CharField(max_length=20)),
                ("votes", models.IntegerField()),
            ],
        ),
    ]
